CREATE TABLE `tokens` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `token` VARCHAR(512) NOT NULL UNIQUE,
    `refresh_token` VARCHAR(512),
    `token_type` VARCHAR(50) DEFAULT 'BEARER',
    `revoked` BOOLEAN DEFAULT FALSE,
    `expired` BOOLEAN DEFAULT FALSE,
    `user_id` BIGINT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
